[package]
name = "rustedbytes-bytepusher-rombuilder"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
glob = "0.3.2"
rand = "0.9.1"

[[bin]]
name = "rom-random"
path = "src/bin/rom-random.rs"